/*
==========================================================
BUSINESS ANALYSIS
==========================================================

Purpose:
This section answers key business questions using SQL to
derive actionable insights from the Olist Brazilian
E-commerce dataset.

The analysis covers customer behavior, sales performance,
seller performance, product performance, payment trends,
and customer satisfaction.
==========================================================
*/

/*
==========================================================
1. CUSTOMER & SELLER DISTRIBUTION
==========================================================

Purpose:
Analyze the geographical distribution of customers and
sellers across Brazilian states. Understanding where
customers and sellers are concentrated provides insights
into market coverage and regional business presence.
==========================================================
*/

-- Count customers by state
-- Which states contribute the most customers?
SELECT
    customer_state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;


-- Count sellers by state
-- Which states contribute the most sellers?

SELECT
    seller_state,
    COUNT(*) AS total_sellers
FROM sellers
GROUP BY seller_state
ORDER BY total_sellers DESC;

/*
==========================================================
2. PAYMENT ANALYSIS
==========================================================

Purpose:
Analyze customer payment preferences by identifying the
most frequently used payment methods. These insights can
help businesses understand customer purchasing behavior
and optimize payment offerings.
==========================================================
*/

-- Count transactions by payment method
-- What payment methods are most popular?
SELECT
    payment_type,
    COUNT(*) AS total_transactions
FROM order_payments
GROUP BY payment_type
ORDER BY total_transactions DESC;

/*
==========================================================
3. REVIEW ANALYSIS
==========================================================

Purpose:
Evaluate customer satisfaction by examining review scores.
The analysis summarizes the distribution of ratings and
calculates the overall average review score.
==========================================================
*/

-- Number of reviews for each review score
-- How are review scores distributed?

SELECT
    review_score,
    COUNT(*) AS total_reviews
FROM order_reviews
GROUP BY review_score
ORDER BY review_score;

-- Calculate the overall average review score

SELECT
    ROUND(AVG(review_score), 2) AS average_review_score
FROM order_reviews;

/*
==========================================================
4. REVENUE ANALYSIS
==========================================================

Purpose:
Analyze sales performance by measuring total revenue,
revenue trends over time, regional revenue distribution,
seller contributions, and average customer spending.
These metrics provide insights into business growth,
market performance, and sales efficiency.
==========================================================
*/

-- Calculate the total revenue generated

SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM order_payments;

-- Calculate monthly revenue

SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    ROUND(SUM(op.payment_value), 2) AS monthly_revenue
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY month
ORDER BY month;

-- Calculate total revenue contributed by customers in each state

SELECT
    c.customer_state,
    ROUND(SUM(op.payment_value), 2) AS revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC;

-- Calculate revenue generated by each seller

SELECT
    oi.seller_id,
    ROUND(SUM(op.payment_value), 2) AS revenue
FROM order_items oi
JOIN order_payments op
    ON oi.order_id = op.order_id
GROUP BY oi.seller_id
ORDER BY revenue DESC;

-- Calculate the average value of an order

SELECT
    ROUND(AVG(order_total), 2) AS average_order_value
FROM (
    SELECT
        order_id,
        SUM(payment_value) AS order_total
    FROM order_payments
    GROUP BY order_id
) t;

/*
==========================================================
5. PRODUCT ANALYSIS
==========================================================

Purpose:
Evaluate product performance by identifying the highest-
performing product categories based on revenue generated
and units sold. These insights help understand customer
demand and product profitability.
==========================================================
*/

-- Calculate total revenue generated by each product category

SELECT
    pct.product_category_name_english AS product_category,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN product_category_translation pct
    ON p.product_category_name = pct.product_category_name
GROUP BY pct.product_category_name_english
ORDER BY total_revenue DESC;

-- Count the number of items sold for each product category

SELECT
    pct.product_category_name_english AS product_category,
    COUNT(*) AS units_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN product_category_translation pct
    ON p.product_category_name = pct.product_category_name
GROUP BY pct.product_category_name_english
ORDER BY units_sold DESC;

/*
==========================================================
6. SELLER ANALYSIS
==========================================================

Purpose:
Analyze seller performance by identifying sellers that
generate the highest revenue and sellers with the highest
number of items sold.

These metrics help evaluate seller contribution and
understand marketplace performance.
==========================================================
*/

-- Identify sellers generating the highest revenue

SELECT
    oi.seller_id,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_revenue DESC;

-- Identify sellers with the highest number of items sold

SELECT
    seller_id,
    COUNT(*) AS total_items_sold
FROM order_items
GROUP BY seller_id
ORDER BY total_items_sold DESC;

-- Display seller location along with performance metrics

SELECT
    s.seller_id,
    s.seller_state,
    ROUND(SUM(oi.price), 2) AS total_revenue,
    COUNT(*) AS total_items_sold
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
GROUP BY 
    s.seller_id,
    s.seller_state
ORDER BY total_revenue DESC;

/*
==========================================================
7. CUSTOMER BEHAVIOR ANALYSIS
==========================================================

Purpose:
Analyze customer purchasing behavior by identifying repeat
customers and comparing one-time customers with returning
customers.

These metrics help understand customer retention and
customer loyalty.
==========================================================
*/

-- Count customers with more than one order

SELECT
    COUNT(*) AS repeat_customers
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(o.order_id) AS total_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(o.order_id) > 1
) t;

-- Classify customers as one-time or repeat customers

SELECT
    CASE
        WHEN total_orders = 1 THEN 'One-time Customer'
        ELSE 'Repeat Customer'
    END AS customer_type,
    COUNT(*) AS number_of_customers
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(o.order_id) AS total_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
) t
GROUP BY customer_type;

-- Calculate average orders placed per customer

SELECT
    ROUND(AVG(total_orders), 2) AS average_orders_per_customer
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(o.order_id) AS total_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
) t;

/*
==========================================================
8. CUSTOMER SATISFACTION ANALYSIS
==========================================================

Purpose:
Analyze customer satisfaction using review scores.
This section evaluates review distribution, positive
feedback percentage, satisfaction by state, and product
category ratings.

These metrics help identify customer experience trends
and areas requiring improvement.
==========================================================
*/

-- Distribution of customer review scores
-- How many 1-star, 2-star, 3-star, 4-star, and 5-star reviews are there?
SELECT
    review_score,
    COUNT(*) AS total_reviews
FROM order_reviews
GROUP BY review_score
ORDER BY review_score;


-- Calculate percentage of positive reviews (3, 4, and 5 stars)
-- What percentage of reviews are 3, 4, and 5 stars combined?

SELECT
    ROUND(
        100.0 * SUM(
            CASE
                WHEN review_score IN (3,4,5)
                THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS positive_review_percentage
FROM order_reviews;

-- Average review score by customer state
-- Which customer states have the highest satisfaction?
SELECT
    c.customer_state,
    ROUND(AVG(orr.review_score), 2) AS average_review_score,
    COUNT(*) AS total_reviews
FROM order_reviews orr
JOIN orders o
    ON orr.order_id = o.order_id
JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_state
ORDER BY average_review_score DESC;

-- Average rating by product category
-- Which product categories receive the highest and lowest ratings?

SELECT
    pct.product_category_name_english AS product_category,
    ROUND(AVG(orr.review_score), 2) AS average_rating,
    COUNT(*) AS total_reviews
FROM order_reviews orr
JOIN order_items oi
    ON orr.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
JOIN product_category_translation pct
    ON p.product_category_name = pct.product_category_name
GROUP BY pct.product_category_name_english
ORDER BY average_rating DESC;
